import React from 'react';
import { Sparkles, Calendar, Bookmark, ArrowRight } from 'lucide-react';
import { SAMPLE_SELFIES } from '../data/mockData';

export default function DashboardView({ activePlan, appointments, onNavigateToPlan, onStartNewPlan, onOpenSalon }) {
  const budget = activePlan?.budgetBreakdown;

  return (
    <div className="py-10 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto space-y-10 animate-fade-in">
      
      {/* Dashboard Top Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-white/10 pb-6">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-rose-500/10 text-rose-300 border border-rose-500/20 text-xs font-semibold uppercase tracking-widest mb-1">
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            Member Personal Workspace
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white font-outfit">
            My <span className="gradient-text-rose">GlowCare Dashboard</span>
          </h1>
        </div>

        <button
          onClick={onStartNewPlan}
          className="px-6 py-3 rounded-2xl text-sm font-bold text-white gradient-btn-primary flex items-center gap-2 shadow-lg"
        >
          <Sparkles className="w-4 h-4 text-amber-300" />
          <span>✨ Create New Glow Plan</span>
        </button>
      </div>

      {/* Top Stats Overview Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Glow Score Widget */}
        <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-2">
          <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Style Harmony Score</p>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-extrabold text-white font-outfit">96</span>
            <span className="text-xs text-emerald-400 font-bold">/ 100 Index</span>
          </div>
          <p className="text-xs text-slate-400">High compatibility across 8 AI agents</p>
        </div>

        {/* Active Plan Widget */}
        <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-2">
          <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Active Glow Plan</p>
          <p className="text-xl font-bold text-white font-outfit truncate">
            {activePlan ? `${activePlan.userProfile.occasion} (${activePlan.userProfile.style})` : 'College Farewell'}
          </p>
          <p className="text-xs text-rose-300">Face shape: {activePlan?.faceAnalysis?.shape || 'Oval'}</p>
        </div>

        {/* Budget Tracker Widget */}
        <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-2">
          <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Beauty Budget Tracker</p>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-extrabold text-white font-outfit">₹{budget?.total || 1900}</span>
            <span className="text-xs text-slate-400">/ ₹{budget?.targetBudget || 2000}</span>
          </div>
          <p className="text-xs text-emerald-400 font-bold">₹{budget?.remaining || 100} remaining balance</p>
        </div>

        {/* Appointments Count */}
        <div className="glass-card p-6 rounded-3xl border border-white/10 space-y-2">
          <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Salon Appointments</p>
          <p className="text-3xl font-extrabold text-white font-outfit">
            {appointments.length > 0 ? appointments.length : 1} Active
          </p>
          <p className="text-xs text-purple-300">Partner salon synced</p>
        </div>

      </div>

      {/* Main 2 Column Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Active Glow Plan Card & Saved Looks (8 Cols) */}
        <div className="lg:col-span-8 space-y-8">
          
          {/* Active Glow Plan Banner */}
          <div className="glass-card p-6 sm:p-8 rounded-3xl border border-rose-500/30 bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900 space-y-6">
            <div className="flex items-center justify-between border-b border-white/10 pb-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-rose-500/10 text-rose-400 flex items-center justify-center font-bold text-xl">
                  ✨
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white font-outfit">Active Glow Plan</h3>
                  <p className="text-xs text-slate-400">Generated by GlowCare AI Agents</p>
                </div>
              </div>

              {activePlan && (
                <button
                  onClick={onNavigateToPlan}
                  className="px-5 py-2.5 rounded-xl text-xs font-bold text-white gradient-btn-primary flex items-center gap-2"
                >
                  <span>View Full Dashboard</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              )}
            </div>

            {activePlan ? (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-sans-body">
                <div className="p-3.5 rounded-2xl bg-slate-950/60 border border-white/10 space-y-1">
                  <span className="text-slate-400 font-semibold block">Face & Hairstyle</span>
                  <p className="font-bold text-white">{activePlan.faceAnalysis.shape} Face</p>
                  <p className="text-slate-300 truncate">{activePlan.hair.cut}</p>
                </div>

                <div className="p-3.5 rounded-2xl bg-slate-950/60 border border-white/10 space-y-1">
                  <span className="text-slate-400 font-semibold block">Outfit & Makeup</span>
                  <p className="font-bold text-white">{activePlan.fashion.outfit.split(':')[0]}</p>
                  <p className="text-slate-300 truncate">{activePlan.makeup.styleName}</p>
                </div>

                <div className="p-3.5 rounded-2xl bg-slate-950/60 border border-white/10 space-y-1">
                  <span className="text-slate-400 font-semibold block">Target Budget</span>
                  <p className="font-bold text-emerald-400">₹{activePlan.budgetBreakdown.total} / ₹{activePlan.userProfile.budget}</p>
                  <p className="text-slate-400">{activePlan.products.length} Products Curated</p>
                </div>
              </div>
            ) : (
              <p className="text-slate-400 text-sm">No active plan generated yet. Launch a plan using the button above!</p>
            )}
          </div>

          {/* Saved Looks Library */}
          <div className="space-y-4">
            <h3 className="text-xl font-bold text-white font-outfit flex items-center gap-2">
              <Bookmark className="w-5 h-5 text-purple-400" />
              Saved Looks Library
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {SAMPLE_SELFIES.slice(0, 2).map((look) => (
                <div key={look.id} className="glass-card p-4 rounded-3xl border border-white/10 flex items-center gap-4">
                  <img src={look.avatar} alt={look.name} className="w-20 h-20 rounded-2xl object-cover" />
                  <div className="space-y-1 text-xs">
                    <span className="font-bold text-white text-sm block font-outfit">{look.name}</span>
                    <p className="text-slate-400">Occasion: {look.occasion}</p>
                    <p className="text-rose-300 font-semibold">Budget: ₹{look.budget}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Right Column: Upcoming Appointments & Quick Links (4 Cols) */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* Upcoming Appointment Card */}
          <div className="glass-card p-6 rounded-3xl border border-purple-500/30 bg-slate-900/90 space-y-4">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <h3 className="text-base font-bold text-white font-outfit flex items-center gap-2">
                <Calendar className="w-4 h-4 text-purple-400" />
                Upcoming Salon Visit
              </h3>
              <span className="text-[10px] uppercase font-bold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                Confirmed
              </span>
            </div>

            {appointments.length > 0 ? (
              <div className="space-y-3 text-xs font-sans-body">
                <div className="p-3 rounded-2xl bg-slate-950 border border-white/10 space-y-1">
                  <p className="font-bold text-white text-sm">{appointments[0].service.title}</p>
                  <p className="text-purple-300 font-semibold">{appointments[0].date} at {appointments[0].time}</p>
                  <p className="text-slate-400">Stylist: {appointments[0].stylist}</p>
                </div>
              </div>
            ) : (
              <div className="p-4 rounded-2xl bg-slate-950 border border-white/10 space-y-2 text-center text-xs">
                <p className="text-slate-300 font-semibold">Signature Blowdry & Style</p>
                <p className="text-purple-300">Sep 28, 2026 at 02:30 PM</p>
                <button
                  onClick={() => onOpenSalon()}
                  className="mt-2 text-xs font-bold text-rose-400 hover:underline"
                >
                  Book Another Appointment
                </button>
              </div>
            )}
          </div>

          {/* AI Specialist Assistant Quick Card */}
          <div className="glass-card p-6 rounded-3xl border border-rose-500/30 bg-gradient-to-br from-rose-950/20 to-purple-950/20 space-y-3">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-amber-300 animate-pulse" />
              <h4 className="text-sm font-bold text-white font-outfit">Need Style Advice?</h4>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-sans-body">
              Use your floating AI Assistant in the bottom right corner to ask questions or dynamically update your active Glow Plan!
            </p>
          </div>

        </div>

      </div>

    </div>
  );
}
